# -*- coding: utf-8 -*-
"""Career_Recommender_eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kq8FhvUU3_yFKqxq2H74JHP_HRA_aE8m
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import random
from sklearn.cluster import KMeans
from sklearn.metrics.pairwise import euclidean_distances, cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer

path = '/content/drive/MyDrive/Datasets24/field_vs_occupation_dataset.csv'
career_df = pd.read_csv(path)

career_df.head()

career_df.count()

# Missing data
missing_values = career_df.isnull().sum()
missing_values

career_df['Current Occupation'].unique()

career_df['Field of Study'].unique()

# distribution of current occupations
plt.figure(figsize=(12, 6))
sns.countplot(x='Current Occupation', data=career_df)
plt.xticks(rotation=90)
plt.title('Current Occupations')
plt.xlabel('Current Occupation')
plt.ylabel('Count')
plt.show()

# distribution of fields of study
plt.figure(figsize=(12, 6))
sns.countplot(x='Field of Study', data=career_df)
plt.xticks(rotation=90)
plt.title('Fields of Study')
plt.xlabel('Field of Study')
plt.ylabel('Count')
plt.show()

# distribution of education level
plt.figure(figsize=(12, 6))
sns.countplot(x='Education Level', data=career_df)
plt.xticks(rotation=90)
plt.title('Education Levels')
plt.xlabel('Education Level')
plt.ylabel('Count')
plt.show()

# Ordinal encoding for Education Level
education_mapping = {
    'High School': 1,
    'Bachelor\'s': 2,
    'Master\'s': 3,
    'PhD': 4
}
career_df['Education Level Encoded'] = career_df['Education Level'].map(education_mapping)

# Replace original column with the encoded
career_df = career_df.drop('Education Level', axis=1)
career_df = career_df.rename(columns={'Education Level Encoded': 'Education Level'})

career_df